# Cordum Edge Claude wrapper — generated by `cordumctl edge init`.
# Loads .\cordum.yaml + env vars then launches the governed Claude session.
# Pass extra Claude args after the literal '--'.
$ErrorActionPreference = 'Stop'
& cordumctl edge claude @args
exit $LASTEXITCODE
